//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmpresaEntities1 : DbContext
    {
        public EmpresaEntities1()
            : base("name=EmpresaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbEstado> tbEstado { get; set; }
        public virtual DbSet<tbListaMaterialesServicio> tbListaMaterialesServicio { get; set; }
        public virtual DbSet<tbMateriales> tbMateriales { get; set; }
        public virtual DbSet<tbMaterialesAsignados> tbMaterialesAsignados { get; set; }
        public virtual DbSet<tbServicio> tbServicio { get; set; }
        public virtual DbSet<tbTrabajador> tbTrabajador { get; set; }
        public virtual DbSet<tbTramitadora> tbTramitadora { get; set; }
    }
}
