//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbListaMaterialesServicio
    {
        public int id { get; set; }
        public int idServicio { get; set; }
        public int idMaterial { get; set; }
        public int cantidad { get; set; }
        public string fecha { get; set; }
    
        public virtual tbMateriales tbMateriales { get; set; }
        public virtual tbServicio tbServicio { get; set; }
    }
}
