//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMaterialesAsignados
    {
        public int id { get; set; }
        public Nullable<int> idTrabajador { get; set; }
        public int idMaterial { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Cantidad { get; set; }
    
        public virtual tbMateriales tbMateriales { get; set; }
        public virtual tbTrabajador tbTrabajador { get; set; }
    }
}
