//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbServicio()
        {
            this.tbListaMaterialesServicio = new HashSet<tbListaMaterialesServicio>();
        }
    
        public int id { get; set; }
        public string idReporte { get; set; }
        public Nullable<int> idTrabajador { get; set; }
        public byte[] Documento { get; set; }
        public int idEstado { get; set; }
        public System.DateTime FAlta { get; set; }
        public Nullable<System.DateTime> FModifEstado { get; set; }
        public int idTramitadora { get; set; }
        public string Vitacora { get; set; }
        public string Descripcion { get; set; }
    
        public virtual tbEstado tbEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbListaMaterialesServicio> tbListaMaterialesServicio { get; set; }
        public virtual tbTrabajador tbTrabajador { get; set; }
        public virtual tbTramitadora tbTramitadora { get; set; }
    }
}
